language: android
android:
  components:
    - build-tools-24.0.1
    - android-24
    - extra-android-m2repository
    - extra-android-support
  licenses:
    - 'android-sdk-license-.+'
  jdk:
    - oraclejdk8

script:
   - ./gradlew build connectedCheck